name: Update Copyright Year

on:
  schedule:
    # Läuft automatisch am 1. Januar um 00:00 UTC
    - cron: '0 0 1 1 *'
  workflow_dispatch: # Ermöglicht manuelles Ausführen

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update copyright year
      run: |
        current_year=$(date +%Y)
        sed -i "s/© [0-9]\{4\}/© $current_year/g" README.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🗓️ Update copyright year to $(date +%Y)"
          git push
        fi
